server:
  port: 8081

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

    open-in-view: false

    show-sql: false

    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/mydb?characterEncoding=utf8&autoReconnect=true&validationQuery=select 1
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: password